### ISSUE TITLE
Source additional appropriate datasets for polity shapes

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#1]
# TODO

- [x] Spend some time to compile a list of datasets, which either are already being linked to Seshat polity IDs by RAs, or could be
- [ ] Send this list to Peter Turchin

# Datasets:
- The video shapes
- [x] [Running reality](https://www.runningreality.org/)
    - This one seems great, and has more of the polities/peoples from the Americas than the video dataset
    - The link to data sources on this [FAQ page](https://www.runningreality.org/docs/about/faq.jsp#data) is broken
    - According to [this page](https://www.runningreality.org/docs/about/faq.jsp#data) "Specific map polygons can be converted to GeoJSON using our app's export feature." - but it's not clear how
- ~~[x] [historical-basemaps](https://github.com/aourednik/historical-basemaps/tree/master)~~
    - This one isn't at the level of resolution we want for Seshat polities
- [x] [Geacron](http://geacron.com/home-en/), some are parts come from mathematica
    - This looks like great, but there's no link to download data anyway, perhaps we can contact them to request it
- GADM: https://github.com/edwardchalstrey1/seshat/issues/6
- May want to merge shapefiles from different resources to get the proper seshat polities

**Comment by edwardchalstrey1** [comment]
GADM: get list of provinces for each country and shapefiles for province and country and hopefully can combine into macro-regions

**Comment by edwardchalstrey1** [comment]
I've send an email to GeaCron:
> Dear GeaCron team,
> I'm writing to enquire as to whether the shape data associated with the world history atlas is available as a download anywhere? We have a project at The Alan Turing Institute in the UK where we would benefit greatly from this kind of data, ideally in GeoJSON format or similar. Right now I'm doing some research into available datasets online and came across this site, which looks like a fantastic resource.
> Best regards
> Ed Chalstrey
> The Alan Turing Institute

Response:
> Hi,
> Thank you for contacting us.
> Unfortunately we do not provide vector files for privacy policy reasons.
> However, we can provide world graphic files for resolution 16384 x 16384
> pixels (Mercator projection) for any date for the last 5000 years. Then,
> you can add any label, icon, line or polygon you consider. The cost of
> each map (year) would be €30 each

**Comment by edwardchalstrey1** [comment]
From the Running Reality website:

![Image](https://github.com/edwardchalstrey1/seshat/assets/5486164/61eab230-87e0-427c-afe2-8eb080d108fb)

I can't install the app on a Turing Mac:



![Image](https://github.com/edwardchalstrey1/seshat/assets/5486164/dfc9cad5-a0d0-4ec2-9f73-59ece131e63f)
