### ISSUE TITLE
Code optimisations and simple feature additions

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#110]
# Done

- Add tests for variable view functions
    - [x] `test_assign_variables_to_shapes`
    - [x] `assign_categorical_variables_to_shapes` 
- [x] See if you can enhance the speed of categorical variables which are slowing everything down
- [x] Retain variable (and any other dropdown) selections on page refresh
- [x] Replace Polity button with a toggle between the two most recently selected variables
- [x] Keep polities highlighted when switching to another var
- [x] Make the bullet text on the side different based on the variable selected
- [x] Rename var/fields between videoshape model, command, view, template to reduce operations and speed up loading
- [x] Investigate why "Personal union of Spanish Empire with Holy Roman Empire" has a border but no fill - is that in the data?
    - Yes: (Holy Roman Empire) is absent for the years that (Personal union of Spanish Empire with Holy Roman Empire) exists. In the bigger GeoJSON it's recorded as a component relationship. For this meta-polity and perhaps others like it, we have a shape with no fill, so I guess it's something Jim just needs to adjust in his code.
- [x] Rename "Unknown" to "Recorded as unknown"
- [x] Split "Uncoded" into "Uncoded" and "No Seshat page"
- [x] Personal union polities will overlap with their sub-polities: Check for 2 seshat_ids and show the border only for the shape of the union polity behind the polity shapes #116 
    - Ed note: if this gets done on 17th April, update VM with latest data and code and send to Jim to forward to the RAs
- [x] Ensure clicking the map to clear legend isn't slow
- [x] Cliopatria 04292024 - need SeshatID version
- [x] Check Cliopatria 04302024 (on the "old" local db)
    - [x] Habsburg Monarchy shape is empty in 1516, but filled in 1512
        - this is ~~not~~ a problem with the geom as revealed by https://geojson.io/
    - [x] Update code to use components rather than composites to get around this
    - [x] Ensure not much slower
    - [x] Ensure personal union clicking still works
    - [x] Make sure polity pages seem the same as the previous drop
- [x] Restore missing personal unions like "Personal union of Crown of Aragon with Crown of Castile" which are not present in the database
- [x] Drop 05082024
    - [x] On VM
- [x] Kingdom of Georgia overlaps 1314?
- [x] Make a dump of the db with the current code and data drop and upload it to the Google drive for Jim to use, the email him the instructions with that link
    - [x] Republic of New Granada
- [x] 05092024 drop
- [x] Ensure sub-polities e.g. Crown of Castile still have their linked Seshat pages
    - `cn_qing_dyn_1` isn't present in my local copy of the database, so should update this
- [x] Update the populate_gadm script so it runs the last SQL steps currently in spatialdb docs
    - [x] Could also make the printout a bit more informative
- [x] In GADM, set the colour of "Modern Caspian Sea" to blue and don't add "Modern". Do this for all seas.
- [x] Try the GADM basemap with a clear fill instead of white
- [x] Clicking away from polities on map is slow, why?
- ~~Rename "Video" to "Cliopatria" in models/tables code and recreate db~~
- [x] Make it so that when you click a polity for a second time, as well as the highlight going away, the tooltip also dissapears

# TODO
- [x] Write tests for the Cliopatria and GADM loader scripts
- [x] Make the increment year buttons change the url year like it does when using the slider or entering a year in the box
- [x] Do we need "Polities" and "Basemap" headers?
- [x] Add a test for `get_polity_shape_content` for a shape that has a union
- [x] Opacity slider set to 0.5 by default
- [x] Add a much bigger text box for the year in the bottom left of the map, comparable in size to the legend, so it's very clear
- [x] Polity dropdown which allows you to select any polity name and it adds it to the legend, but if it's not in the current year it goes to the first year of that polity
- [x] Make sure the categorical variable selection button is not there by default or greyed out
- [x] Add link to Seshat page from tooltip
- [x] Add a "Switch to" button for categorical variables too
- [x] Add a "hide uncoded" checkbox
- [x] Order categorical variable dropdown by number of polities that have them, or keep alphabetical order but split by popularity
- [x] Clicking a polity to highlight it should also highlight the chain of preceding and succeeding polities where they exist
- [x] Add increments for the +/- buttons
    - This could be the same number as the value of the speed
- [x] Make world map fonts/themes up to date with the rest of the Seshat site
- [x] Have a new radio button to switch between "Polity" and other variables
- [x] Make sure JS functions are named clearly e.g. things that refer to "slider" should specify if it's the year or play rate slider
- [x] Make it so adjusting the speed doesn't play the animation by default, you have to click the play button
- [x] Add a legend to the Polity page map for when "Polity components" is selected, which should always be populated with all the colours, but disappears when the dropdown is set to "Full polities"

# Final TODOS

- Create Wikipedia links
    - Replace the shape `wikipedia_name` spaces with underscores and append to `https://en.wikipedia.org/wiki/wikipedia_name`
    - [x] Add to World Map popup
    - [x] Add a link somewhere on the Polity Page tooltip
- [x] Could have a single play/pause button that switches symbol
- [x] Change the start and end buttons to skip forward and backwards symbols and add them to polity pages too

**Comment by edwardchalstrey1** [comment]
# Years to check for personal union polities

- 1305
- 1535
- 1475

TODO:
- [x] Don't highlight by default
- ~~Do highlight when clicking~~
    - At the moment it only works when you subsequently increment the year, despite my attempt with the `runTwice` flag for `plotPolities()`
- Change it so that when the union has an active year, the colour of both polities:
    - [x] switch to the union colour
    - [x] and the legend just has the union
- [x] When clicking a sub polity or a union in any given year then changing to a year that has the opposite, the legend and highlight should persist but switch 
- [x] Get the runTwice feature to work such that clicking a union polity highlights all sub polities
- [x] Rename "Seshat page missing" to "No Seshat page"
- [x] Make it so clicking a union (or clicking to a polity and changing the year to where its a union) and then changing to a new year where it's no longer a union, shows all the sub polities now they are separated, not just the one clicked
- [x] Make sure legend doesn't show the union when clicking a sub-polity unless the union is active in the year given

**Comment by edwardchalstrey1** [comment]
No Seshat page
