### ISSUE TITLE
Shape display colour, name and clicking issues/ ideas

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#130]
# Conundrums
- There are some shapes that are members of two different polities, for example a shape called “French Third Republic” has "Member_of": "(Second French Empire);(French Third Republic)" and similar for “Kingdom of Spain” and “Spanish Empire”, but whereas in the latter the same SeshatID applies to shapes from either Kingdom of Spain or Spanish Empire for a given year, this breaks down for France where we have the French Third Republic Seshat-linked but Second French Empire isn’t. So, whilst I tried to use SeshatID as a basis for colour choice (where present), this breaks down a bit with this inconsistency. I’m not sure what the solution is here
- How should we handle overlapping shapes? It may be better to get other people to report these issues rather than trying to solve everything. Focus on other tasks.

# TODOs

- [ ] Ensure clicking works as expected in all cases:
    - In 1474, why does clicking "Khanate of Sibir" (west Russia) highlight so many others? - there are many examples of this, but you can get rid of them by clicking
    - In 1565 clicking Spanish Empire highlights all components, but in 1758 it doesn't
- [ ] Figure out a way to make sure clicking overlapping layers clicks both - this might be something you can just ask copilot how to enable for geojson layers regardless of their order
- [x] Have a "clear legend" button or a minus button on each legend item
- [ ] Make it so that clicking a legend item changes the border colour to red (or something appropriate)
- [ ] Have the "Seshat Duration" and "Cliopatria Duration" in the tooltip to highlight mismatches (maybe only as a developer feature) see #28 
- [ ] Ensure union legend clicking makes sense (see 1475 Crown of Castille etc)

**Comment by edwardchalstrey1** [comment]
Update: the clicking rules for personal union polities are currently commented out in the world map template
