### ISSUE TITLE
Bug: Present/absent variables don't correctly represent dates

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#149]
Display of the present/absent values were not reflecting any date specific restrictions.  Here is an example.

For the Dutch Empire (which is named Dutch Republic in the shape, likely to change) the db states that before 1673 they did not have professional military officers, and then they did (see the year_from/year_to bits…if they are empty then it applies to the entire polity year_from/year_to dates):

subsection|variable_name|year_from|year_to|polity_name|polity_new_ID|polity_old_ID|value_from|value_to|confidence|is_disputed|is_uncertain|expert_checked|DRB_reviewed
Professions|professional_military_officer|1648|1672|Dutch Empire|nl_dutch_emp_1|nl_dutch_emp_1|absent||Confident|False|False|False|
Professions|professional_military_officer|1673|1795|Dutch Empire|nl_dutch_emp_1|nl_dutch_emp_1|present||Confident|False|False|False|

![Screen Shot 2024-05-17 at 10 23 11 AM](https://github.com/edwardchalstrey1/seshat/assets/5486164/4b74c853-2a6f-463b-8af1-5829b63170fb)

**Comment by edwardchalstrey1** [comment]
# TODO:

- [x] Why is the colour not showing properly for 1673 professional military officer Dutch Republic until after all shapes have loaded - need to convert the JS to get the dict structure properly
- [x] Ensure we get all the values for `coded_value` variables 
- ~~Use `shape[variable_formatted + '_dict']` always~~ we still use the non dict version for cases where no years are set
- ~~Rename `shape[variable_formatted + '_dict']` to `shape[variable_formatted]` and remove what was already there~~
- [x] Update tests
- [ ] Refactor
- [x] Do the same for categorical variables
- [x] Ensure RT suppressed
- [x] Make it so all absent/present options are shown on the tooltip, with years?
- [x] Ensure 'A~P' actually reads 'Absent then Present'
