### ISSUE TITLE
Cliopatria explorer notebook

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#153]
# Jupyter notebook alternative idea as a tool for RAs/consumers to use to explore Cliopatria quickly

- Load the Clioaptria and GADM files directly, use GeoPandas (perhaps 1.0) etc to be super fast
    - See #152 and https://hackmd.io/@edchalstrey/rkIiMZz4A
    - GeoPandas 1.0 can use new features of GEOS/Shapely that allow simplification without losing the tessellation of shapes on the map
- Use Jupyter widgets for the same sort of controls as Seshat website, for polygons plotted on map
- Combination of populate_videodata command logic and views logic would need to be done as functions to use here
- Could use existing colours in Cliopatria to save time on colour generation
- Make instructions on how to load the notebook, so all RAs need to is open it in the right Python environment, pass the paths to Cliopatria and GADM files and run it
- Could have a Binder version so all they need to do us provide the data
- If you wanted to load GADM fast: GeoPandas 1.0 can read geopackage files really fast (pyogrio/pyarrow)

Maybe the way to do it is simply first:
1. Load the GeoJSON efficiently
2. Plot a given year on the map, determined by the code cell
3. Add a widget for sliding the years, playing through
4. Add a filter function to avoid composites etc

# Tools to try out

- GeoParquet as an alternative to GeoJSON
- GeoPandas 1.0
- Lonboard
- GeoArrow

[GeoPython notes](https://hackmd.io/@edchalstrey/rkIiMZz4A)
![20240528_122134](https://github.com/edwardchalstrey1/seshat/assets/5486164/25b7caaa-67a2-4175-bb9e-b11f95cb3fcf)

**Comment by edwardchalstrey1** [comment]
# TODO
- [x] Add version number for Geopandas in requirements
    - `geopandas-1.0.0a1+50.gfef0c24`
    - [x] Test with current Geopandas release
- [x] Figure out how to not have a duplicate of the folium map **EDIT:** Does Jupyter do this?
- ~~Refactor the `create_map` func so instead of recreating the map, it removes the current layers and then just displays it again~~
- ~~Make the play and pause buttons work~~
- [x] Add a tooltip that simply shows the name
- [x] Refactor the `cliopatria_gdf` func to be inline with what we do in `populate_videodata` on namings and ignoring shapes
- [x] Extract the name handling and end year extraction to separate functions
- ~~TRY THE GEOPANDAS SIMPLIFY that keeps tesselation with the full dataset~~
    - this doesn't work that well, but do we even really need to simplify the geometries? **Edit:** looks like it might not be needed
