### ISSUE TITLE
Move end years code generation to Cliopatria

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#156]
The `populate_videodata` command script has a part where we generate end years for each shape, based on some logic involving the start year and the years in the name_years.json - it might be better to forward this to Jim Bennett/ Cliopatria team for them to use to add a field for the end_year to each shape, meaning that we'd only need a single GeoJSON for Cliopatria, and the command script could also be simplified

# TODO

- [x] Write a script that does the above - see #167
- [x] Send to Jim et al
- ~~Should we just use the colours in the dataset? How are these being generated?~~
- [x] https://github.com/Seshat-Global-History-Databank/seshat/issues/19
- [x] Once Cliopatria has end years included, update the `populate_videodata` command script
- [x] Make the `populate_videodata` command script accept a single geojson file and update rst doc to reflect this
- [x] There is a problem with using GeoPandas as part of the `populate_videodata` command script in that it causes a segmentation fault (this is something to do with conflict between Geopandas and GEOS). Instead, move the function that converts the geoJSON in geopandas by adding extra fields to a new conversion script that spits out a new GeoJSON. This can then be loaded much more quickly by the webapp and notebook since the colours are already generated
    - [x] Make the Cliopatria notebook and the command script use the exact same code - call it the cliopatria handling module

**Comment by edwardchalstrey1** [comment]
Update: Jim is incorporating this into the Seshat code
