### ISSUE TITLE
Handle colours for polity components better

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#163]
> One thing I thought is that it would be great if the individual polities of composites would have different colours, For example all the small states of the HRE which are selectable now just have the same color, not sure if this is possible.

The thing this raises is whether the current colouring regime of always going for the highest level, including for personal unions should be overturned.

Downside could be this causes legend chaos

Linked to #130 

# TODO

- Ensure that shapes do not overlap. Toggle between components view (lowest level) and full polity view
  - [x] In notebook
  - [x] On world map
      - [x] Ensure legend is based on switchPolitiesComponents
      - ~~and says "Selected components"~~
  - [x] On polity map
- [x] Toggle only visible when 'Polity' selected on variable dropdown
- [x] Remove "polity" field from Videoshapefile
- ~~Add test for the `cliopatria_gdf` function in `convert_data.py`~~
- [x] Update dev site
- [x] After merging a PR with these changes, email Jim Bennett from Cliopatria team to suggest that where personal union composites include a bracketed component that would otherwise be a high level polity, the polity has an entry in the `MemberOf` field for the personal union - this is a current inconsistency that makes it hard to display the personal union shapes without overlapping. Also mention to majid he will need to re-run migration.
- [x] Update tests

**Comment by edwardchalstrey1** [comment]
Right now, I’m setting the colour based on the highest level composite, an alternate approach would be to set colour on the lowest level sub-polities, in which case I’d want to limit clicking to just highlight (and add to the legend) the sub-polity. An advantage would mean that on a Seshat polity page, you would get some Seshat polities that have several colours, so it’s clear to the viewer that sub-polities exist. I think on the world map however, you’d lose sight of large empires doing it this way, e.g. the British empire would look like a few separate entities across the world.

**We could even assign each shape two colours and have the ability to toggle between the 2 settings, one where all the shapes in a composite have the same colour, and one where they vary based on sub-polity. That might be quite nice actually – best of both worlds!**

**Comment by edwardchalstrey1** [comment]
The way we handle overlapping shapes of components and members is a bit inconsistent currently
