### ISSUE TITLE
Improve year selection on maps

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#165]
From Jim Bennett:
> I’d like to have another numeric entry field next to ‘Enter year’ that is the Time step: for the +/- buttons. That way I can change it to 10 or 100 or 500 for fast jumps per button press.  Alternatively having a year bar at the bottom of the display ala Old Maps Online (OMO) might eliminate the need for text input altogether.

Having the slider big at the bottom of the screen could work nicely if it lines up with a printed x axis with the years

- [x] World map
- [x] Polity map

# TODO

- [x] Make tickmarks line up properly
- [x] Why are tick positions wrong before loading the full set of years?
- [x] Why does the selected year change from the default?
