### ISSUE TITLE
Presentation fixes 18th June '24

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#166]
- [x] If year from and year to are not recorded for absent/present or categorical vars, substitute in the duration years by default
- [x] Change how the unocded/ no Seshat page for absent/present or categorical vars are handled - Jim's suggestion:
    - > In the current variable display you have uncoded as a sort of pink but I too easily begin to think of that as absent (red) without another compelling example at the same time.  I propose that you display uncoded in grey like ‘no seshat page’ (but give it a black border to indicate there is a page). Subtle yes but I think less misleading and it tells RAs/experts where missing codes are more easily.  The legend should just list ‘Uncoded’; clicking on a grey shape will tell you if you have a seshat page or not.
    - One problem with this could be that having the GADM borders underneath historical polities that both have black borders could look a bit confusing - so give polities a grey border?
    - Solution: Keep the coloured borders for polities, but just make uncoded grey and drop from legend
- > I see the ‘coded unknown’ has a black border which stands out well.  Why don’t the present/absent/present_to_absent/absent_to_present have a similar black border rather than their (same) color
    - Answer: when you have GADM selected there are already black borders for the current borders 
- [x] Improve or comment out the 'Switch to' button
    - > ‘Switch to’ button confusing and would drop it for the moment
- The legend clicking is a bit buggy, should we remove it for now and restore it later when we get to #130 ?
    - > I would drop The legend altogether in Polity mode.
    - Answer: I don't think this should be removed as it it works well for looking at a selection of polities of interest, especially where colours are similar
- > Drop the Opacity slider as this doesn't help
    - Answer: I think this should be kept so the user has max controls over the visuals
- [x] Consider restoring the years/second value in the animation options (the problem before is this won't be very accurate as it slows down when more shapes are displayed)
    - [x] Do this for polity pages too
- [x] > I think you can eliminate the ‘instructions’ since it is easy enough to discover everything except the double-clicking.
- [x] Can we lock the zoom so that you can't go further out than one Earth?
- ~~Make GADM basemap 0.5 white fill instead of blank~~
    - Can't remember why I said this 
- Make world map fonts/themes up to date with the rest of the Seshat site - moved to #110
- [x] #165 
- Add increments for the +/- buttons - moved to #110
- [x] Make polity map twice as big
- [x] Tidy world map side panel including adding the selected year in the same font as on the polity map

**Comment by edwardchalstrey1** [comment]
Bugs

- [ ] Some of the shapes in 1470 France are orange for Canal when they should (probably) all be yellow

**Comment by edwardchalstrey1** [comment]
Idea:
- [ ] Rename the section "Polities" to say something like "Colour by Seshat variables" or have a new radio button to switch between "Polity" and other variables

**Comment by edwardchalstrey1** [comment]
# TODO

- [x] Complete the items above
- [x] Merge #170
- [x] Update the middleware branch and test site
- [x] email Jim Bennett with responses and bug report
