### ISSUE TITLE
Scope map-based website navigation tool

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#3]
# Initial idea

1. Use shapefile data to make a map visualisation similar to http://geacron.com/home-en/ in Python that can be included as a page on the Seshat Django webapp
2. Clicking (or highlighting) the polity shapes should link to their information pages
    - e.g. clicking the shape over Crete when time slider is on 1,300 BCE should link to http://seshat-db.com/core/polity/64

### 19th October suggestions
1. Visualiser tool could switch between different data resources
2. Later on: the map web tool can take suggestions on boundary edits by logged in users
3. ~~Might be worth having a separate db for the spatial data~~ - **Edit:** probably easier to have linked tables in the main db if this is feasible, see #4 

### TODO:

- [x] Research what the best tools are for map visualisation
- [x] List complete set of features that this should have
    - [x] Time selecter
        - [x] Start/end range
        - [x] Individual years, maybe as a slider or number entry if easier?
    - [x] Modern countries
    - [x] #16
    - [x] #17
    - https://github.com/edwardchalstrey1/seshat/issues/11
    - [x] #18
    - [x] Highlight polity reveals some basic info
    - [x] Make the colour shade of the shape based on the polity
        - [x] Keep the colour choice consistent
            - [x] #19
    - [x] Add a play button that will advance from the currently selected year at a rate of X years/ second

**Comment by edwardchalstrey1** [comment]
Another resource: https://github.com/aourednik/historical-basemaps/tree/master

**Comment by edwardchalstrey1** [comment]
# Meeting notes from 19th October

https://hackmd.io/@edchalstrey/SysdAh0W6

**Comment by edwardchalstrey1** [comment]
# Ideas
- Colour shape based on variable present

**Comment by edwardchalstrey1** [comment]
### Notes 20th November

- Macrostate: Single time selection by default not range, but keep range as an option
- GADM: have second level province/state
- Have a view with both Macrostate and GADM
- The linked video dataset that will replace macrostate dataset is not ready yet, very soon

So a good v1 of the tool could have the features of modern country/province plotted in one colour (or over lapping sensibly) and the polities for a year on top. Double clicking the polity would go to the polity page (with some info on single click) and the modern day would have the info we currently have, but only the top 2 levels of country and province.
