### ISSUE TITLE
Design method for importing shapefile data into Seshat and use with initial dataset

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#4]
- [x] Create new postgres db that can handle the shapefile format, using PostGIS
- [x] Create a script that populates the db with shapefiles
- [x] Create a basic map view that can be used in advance of doing #3 - just to show connection to be works nicely
    - [x] Time slider
        - [x] add macrostate_data csv to db
- [x] Make it possible for the shape tables to be in the same database as Seshat stuff
- [x] Create a django/model class such that it automatically creates database tables - via [migrations](https://docs.djangoproject.com/en/4.2/topics/migrations/). This should probably replace the script that populates the db with shapefiles.
- Shapefile datasets should be added where each shape has a Seshat polity ID. Probably separate tables for each dataset.
    - [x] Start by attempting to add the subset of [shapefile data](https://drive.google.com/file/d/16hC7usvuZa5KyzFg6T-_t4AJ7j_47IeM/view?usp=share_link) labelled with polity IDs by James Bennet
- ~~Ultimately this db might live another server on AWS with PostGIS and API connections to the website, linking via Seshat polity IDs~~ unsure why this was proposed?

**Comment by edwardchalstrey1** [comment]
# Stage 1: Website navigation tool

Website navigation tool: Django map with link to Polygons and time sliders which link to pages on the existing website, could also show capitals and anything else with coordinates

# Stage 2: Data exploration tool

Data exploration tool: Integrate a 3rd party tool such as Peripleo
