### ISSUE TITLE
Cliopatria on Seshat live site

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#89]
### TODO

- [x] **Jim** to submit a version of Cliopatria we are happy to go live - **Update:** See https://github.com/Seshat-Global-History-Databank/cliopatria
- **Majid** to
    - [x] Set up new AWS VM and pull from new repo dev branch: https://github.com/Seshat-Global-History-Databank/seshat
    - [ ] Change seshat-db.com to point to seshatdata.com VM or set up a new one with the same [setup](https://seshat-global-history-databank.github.io/seshat/admin/setup/cloud/CSH_manual.html)
    - [ ] Ensure that the latest db dump is uploaded to the new production VM and [spatial datasets are loaded](https://seshat-global-history-databank.github.io/seshat/admin/setup/spatialdb.html)
    - [ ] Test everything works as expected, e.g. users can login and make edits as expected

**Update:** seshatdata.com has maps. Aim to decommission old VM with seshat-db.com when Majid returns from parental leave. See active sites here: https://github.com/Seshat-Global-History-Databank/seshat/wiki/Seshat-sites

**Comment by edwardchalstrey1** [comment]
Closed in favour of https://github.com/Seshat-Global-History-Databank/seshat/issues/91
