### ISSUE TITLE
Extract the map tool as a separate codebase

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#90]
### TODO:

- [ ] Determine dates this would be needed by
- [ ] Determine which of the below we will actually do
- [ ] Ensure the Cliopatria format is stable so the loader code doesn't diverge too much

### Ideas
- An open software package, on GitHub ~~perhaps under the ATI org~~
- Could be used by others who want to create a map of nations and empires
- Shows Cliopatria data and GADM, but not Seshat
- Should be able to avoid divergence of code from the Seshat repo version since subsequent development will be primarily around visualising other Seshat variables, rather than updating the look and feel of the map viewer itself
- Can include steps to run locally or on the cloud
- JOSS paper?
- Links to most recently published version of Cliopatria dataset - with explainer that the Seshat project will result in updates to this in future
- Could include Jim Bennet code for viewing Cliopatria
- Could be extensible to other shape datasets, with a guide on how to add new ones
    - Might be a good idea to not call the new repo Cliopatria
    - Could have a GADM viewer that displays down to the lowest authorities
- Could there be an installable app version? As oppose to a website
- Make it well documented and easy enough to use for Jim and the RAs
- Dockerise?

### Dates

- Usable ~~by early June~~
- Published by... (I think worry about this once it's ready)

**Comment by edwardchalstrey1** [comment]
Jim Bennet:
> I could also make a version of my KML/Google Earth emitter available in the same repository in case people want to view it that way.

**Comment by edwardchalstrey1** [comment]
Alternative idea - (do this later maybe still tho): should people just use the Seshat repo instead since there's instructions

**Comment by edwardchalstrey1** [comment]
# Jupyter notebook alternative idea as a tool for RAs/consumers to use to explore Cliopatria quickly

#153

**Comment by edwardchalstrey1** [comment]
Superseded by #153
