### ISSUE TITLE
Add current ways of working to Seshat project readthedocs

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#91]
# Pre-requisites

- [x] https://github.com/Seshat-Global-History-Databank/seshat/issues/23 so we can show RAs progress so far when consulting them on their respective pages

## Docs pages
- [x] ~~Could look similar to https://alan-turing-institute.github.io/trusted-research/~~ Live at https://seshat-global-history-databank.github.io/seshat/index.html
- Pages for processes for each role
    - [x] Seshat Admin
        - [x] GitHub workflow
        - [ ] Database backup procedure
        - [ ] Include a schema map of the db
        - [x] Setup documentation
        - [ ] General notes on Django etc
        - [x] How to edit readthedocs
    - [x] Research Assistant (could we work with Matilda on some of these in advance of the workshop?)
        - [ ] Link to example notebooks for using the Seshat API and Cliopatria GeoJSON
        - [ ] Data cleaning methods: page with links to repos/notebooks with code that can be run to reproduce data extracts used for research projects/papers, with the latest data from the website
        - [ ] Data analysis: links to notebooks/repos/scripts from research projects showing some analysis in Python/R
        - [ ] How the Seshat comment system works generally (is this recorded anywhere already?)
        - [ ] How to use the Seshat comment system to make requests of the Seshat Admin(s)
        - [ ] How to make database edits
        - [ ] How to make edits to Cliopatria [#140](https://github.com/Seshat-Global-History-Databank/seshat/issues/32)
        - [ ] How to edit readthedocs for RAs, which could be a simpler approach than described above for an admin familiar with Git, involving editing the page in GitHub (which should trigger a PR automatically for non-admins of the GH repo?)
    - [x] Seshat Expert
        - [ ] How to use the Seshat comment system as a Seshat Expert (currently disabled)
    - [x] Public User (maybe don't need but could include some "how to use Seshat guides")
        - [ ] How to suggest edits via the Seshat login system (this page should be linked to from "Seshat Expert" too)
    - [ ] Institutions and people
        - [ ] Who to contact for what, and who to contact when they're on leave. e.g. who at CSH should be contacted to restart VM if the site is down and Majid is on leave
        - [ ] Need to determine the appropriate level of public facing info on contact details (or if this is only relevant for project members, write it down somewhere private and link to it)
    - [ ] (Optional) A "Legacy Resources" page with links to any and all websites, wikis etc of the Seshat project
    - [ ] Code of conduct

## TODO

- [x] Consult with Seshat project people on how they are doing things currently for first draft of pages
- [ ] Create separate issues for specific docs pages above
- [ ] Do a first draft of all these pages
- [ ] Make it so that anyone in the project can update the readthedocs and can give others access (i.e. ensure all RAs have write access)

**Comment by edwardchalstrey1** [comment]
More ideas: https://github.com/MajidBenam/seshat/issues/5

**Comment by edwardchalstrey1** [comment]
If we do the above before the as yet unscheduled Seshat Autumn get together, this can guide what we need to do for #141

**Comment by PieterFrancois** [comment]
Hi Ed,

The four RAs to get in touch with are:
'Enrico Cioni' ***@***.***>
Samantha Holder ***@***.***>
J.Z. ***@***.******@***.***>
'Jenny Reddish' ***@***.******@***.***>

Once a draft has been created I think quite a few other eyes will have to go over it, e.g. myself, Peter, Dan, …. . I am happy to lead on this editing process.

Best wishes,
Pieter




From: Ed Chalstrey ***@***.***>
Date: Thursday, 20 June 2024 at 05:11
To: edwardchalstrey1/seshat ***@***.***>
Cc: PieterFrancois ***@***.***>, Mention ***@***.***>
Subject: Re: [edwardchalstrey1/seshat] Create Seshat project docs site/ online handbook (Issue #91)
Notes from Seshat meeting 19th June 2024

  *   In the long run, would be great if we could manage a CI/CD pipeline that allows approved Seshat developers at Turing or elsewhere to push changes to the live site, which is managed at CSH on AWS. If there was a GH action that updated the VM on push to main.

     *   Related to #79<https://github.com/edwardchalstrey1/seshat/issues/79>

  *   Majid will be on paternity leave for ~2 months from ~4th August

     *   He will aim to integrate maps to the live site before then, however this will require setting up a new cloud VM (he aims to do so in a more reproducible way that previously) - the goal here would be to set everything up first, then only switch the domain to the new IP address once the v1 Cliopatria shape dataset it confirmed as ready to go live. It's possible this won't get done before he goes on leave as Pieter was also suggesting some other priorities.

  *   There are some RAs outside of the group who have developed Cliopatria who already wish to get involved with making/suggesting shape edits

     *   [name=Ed] My thoughts here is it would be great to get an initial docs page from the Cliopatria team on their current process, however clunky, before attempting to create a new one

TODOs

  *   @edwardchalstrey1<https://github.com/edwardchalstrey1> @kallewesterling<https://github.com/kallewesterling> @MajidBenam<https://github.com/MajidBenam> to meet to scope required docs pages and desired/optimal GH workflow

     *   [name=Ed] It may be worth taking advantage of the time where Majid is on leave to have a process ready for when he returns; we can then spend a bit of time to train him in the new workflow and how to collaborate with external developers effectively via GH

  *   @PieterFrancois<https://github.com/PieterFrancois> to provide complete list of people to get in touch with regarding process pages for the different roles

**Comment by edwardchalstrey1** [comment]
The people to get in touch with are:

| Person | Email | Institute | Role |
| --- | --- | --- | --- |
| Enrico Cioni | ecioni@turing.ac.uk | Turing | RA |
| Samantha Holder | samantha.louise.holder@gmail.com | Pieter: "works as a casual Research Assistant for us, so not formally attached, more a consultancy role" | RA |
| Jakob Zsa | jakob.zsa@gmail.com | CSH | RA |
| Jakob Hauser | jakob@hauser.earth | CSH | RA (NLP) |
| Jenny Reddish | reddish.jenny@gmail.com | CSH | RA who has worked on Cliopatria |

Pieter: "Once a draft has been created I think quite a few other eyes will have to go over it, e.g. myself, Peter, Dan, Jim …. . I am happy to lead on this editing process. "

**Comment by kallewesterling** [comment]
thanks @edwardchalstrey1 !

**Comment by edwardchalstrey1** [comment]
@kallewesterling is documentation something you're interested to take the lead on? I've updated this issue to be clearer with what I intended: basically to get in touch with the current key user types and specific people on the project and write down their current processes in the docs, but also ensure there's a process by which they can edit (or at least suggest edits) going forward

**Comment by kallewesterling** [comment]
Sure thing! Sounds like something that'd be typical RAM work, to be fair. I might just do some user interviews!

**Comment by edwardchalstrey1** [comment]
> Sure thing! Sounds like something that'd be typical RAM work, to be fair. I might just do some user interviews!

Perfect, that sounds like what I had in mind 👍

**Comment by edwardchalstrey1** [comment]
Another quick thought: once the above is done and we have both a) a rough documentation of current processes and b) a rough plan of how the project should work going forward, in a sustainable manner, it might be worth inviting Pieter up to Turing for half a day to figure out a plan of action for how to improve/ implement the processes

**Comment by edwardchalstrey1** [comment]
One additional comment from our meeting with Majid is that we should document how the RAs currently use the comment system in Seshat to make requests directly to Majid.

@kallewesterling I've deleted some of my comments above and hopefully everything here is clear now - but feel free to reopen this on the new repo according to one the templates if that would help to structure it better

**Comment by edwardchalstrey1** [comment]
Closing as replaced by:
- https://github.com/Seshat-Global-History-Databank/seshat/issues/101
- https://github.com/Seshat-Global-History-Databank/seshat/issues/102
