### ISSUE TITLE
Visualise spread of Seshat variables on world map

### ISSUE THREAD

**Issue by edwardchalstrey1** [edwardchalstrey1/seshat#94]
# TODO

- [x] Investigate how useful these visualisations are to RAs - Ed has emailed the group on 13th August 2024
- [ ] Find a way to scan the database for all variables
- [ ] Are some variables not worth visualising?
- [x] Maybe should focus on variables of interest to RAs
- [ ] Create proper issues for all of the below
- [ ] Turn this issue into a milestone or epic

### Variables

- Present/absent vars
    - [x] Present/absent vars that are dated
        - e.g. see Ottoman Empire I (core/polity/174) "Gunpowder Siege Artillery"
    - [ ] Human sacrifice vars
- Categorical vars:
    - [x] #109
        - [x] Visualise the years for categorical vars
        - [ ] Add the years for categorical vars to the tooltip (this could get messy) - check if worth doing as there looks to be virtually no years recorded in the db for language variables at least (there is one entry in the db where the `language` `year_from` and `year_to` are not null and one `linguistic_family` and they are the same as the polity years `es_spanish_emp_2`)
    - [ ] #115 
    - [ ] Religion
        - All the categories under "Religion"
        - "Official Religion" and "Elites" Religion under `RT -> Religious Landscape`
    - [ ] "Supracultural Entity"
    - [ ] "Government Restrictions -> Frequency of Governmental Violence Against Religious Groups"
    - [ ] "Societal Restrictions -> Frequency of Societal Violence Against Religious Groups:"
    - [ ] "Professions" -> Source of Support"
    - [ ] Any others that use `FREQUENCY_CHOICES`, `PREVALENCE_CHOICES` or `ORDER_CHOICES` in RT models
    - [ ] Human sacrifice categorical vars (look at models.py)
- Continuous vars:
    - [ ] Social Scale
- Numerical category vars:
    - [x] Hierarchical Complexity
- Complicated vars and var groups:
    - [ ] Identity and location
        - Capitals were already implemented, but may be worth thinking of a different way to visualise that makes the uncoded clearer, as well as displaying original/alternative names etc. This can probably all be stuff that is there on the "Polity" dropdown selection
    - [ ] Political and Cultural Relations
        - Succeeding/Preceding entities could be chained?
        - Others here all need to be looked at carefully
    - [ ] "Religious Landscape -> Widespread Religion"
    - [ ] Power transitions (these seem to have some overlap with the Leaders etc in Cliopatria)

**Comment by edwardchalstrey1** [comment]
As well as boolean vars, we may want to create an equivalent of the world map where colour is based on supracultural entities or religions etc

**Comment by edwardchalstrey1** [comment]
Use emojis?

**Comment by edwardchalstrey1** [comment]
Languages:
- [ ] Assign the language colour to the shape table
- [ ] Ensure the legend does not go off the screen
    - Could actually make it like polities where you have to click to populate the legend

**Comment by edwardchalstrey1** [comment]
# Update from November 2024 Seshat workshop

- This is valuable to do
- Peter Turchin has suggested that Hierarchical complexity (and SC generally) would be a good one to prioritise
